# Generated by Django 5.0.1 on 2025-03-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_user_type'),
        ('app', '0002_user_full_name_alter_user_user_type'),
    ]

    operations = [
    ]
