# Generated by Django 5.0.1 on 2025-05-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_merge_20250307_2312'),
        ('app', '0005_alter_user_options_alter_user_address_and_more'),
    ]

    operations = [
    ]
