# Generated by Django 5.0.1 on 2025-09-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20250512_2251'),
        ('app', '0012_alter_user_email'),
    ]

    operations = [
    ]
