# Generated by Django 5.0.1 on 2025-10-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_merge_0006_merge_20250512_2251_0012_alter_user_email'),
        ('app', '0013_order_admin_approval_date_order_admin_approved_and_more'),
    ]

    operations = [
    ]
