# Generated by Django 5.0.7 on 2025-10-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_payoutrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='admin_notified_of_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='confirmed_by_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='requires_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('payment_confirmed', 'Payment Confirmed'), ('awaiting_approval', 'Awaiting Admin Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
