# Generated by Django 5.0.7 on 2025-10-25 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_notification_admin_notified_of_confirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='payout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='payout_reference',
            field=models.CharField(blank=True, help_text='Transaction ID or check number', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
