# Generated by Django 5.0.7 on 2025-10-28 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_payoutrequest_approved_at_payoutrequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='payment_details',
            field=models.JSONField(blank=True, default=dict, help_text='Payment method details (e.g., account number, email, etc.)'),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('wise', 'Wise (TransferWise)'), ('other', 'Other')], help_text='Preferred payment method for payouts', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='VendorEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, help_text='Total earnings from all completed orders', max_digits=12)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance available for withdrawal', max_digits=12)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance from pending payout requests', max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount withdrawn', max_digits=12)),
                ('total_orders', models.IntegerField(default=0, help_text='Total number of completed orders')),
                ('last_payout_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vendor Earnings',
            },
        ),
    ]
