# Generated by Django 5.0.7 on 2025-10-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_user_options_user_payment_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('visa_card', 'Visa Card (Stripe)'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('wise', 'Wise (TransferWise)'), ('other', 'Other')], help_text='Preferred payment method for payouts', max_length=20, null=True),
        ),
    ]
