# Generated by Django 5.0.7 on 2025-10-30 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_user_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(help_text='Unique receipt number', max_length=50, unique=True)),
                ('transaction_id', models.CharField(help_text='Payment gateway transaction ID', max_length=200)),
                ('payment_method', models.CharField(help_text='visa_card, bank_transfer, etc.', max_length=50)),
                ('payment_destination', models.JSONField(help_text='Masked account/card details')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('payout_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='app.payoutrequest')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
