# Generated by Django 5.0.7 on 2025-12-08 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_payoutrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('theme_preset', models.CharField(choices=[('minimal', 'Minimal'), ('vibrant', 'Vibrant'), ('dark', 'Dark'), ('classic', 'Classic')], default='minimal', max_length=20)),
                ('primary_color', models.CharField(default='#10B981', max_length=20)),
                ('accent_color', models.CharField(default='#111827', max_length=20)),
                ('about', models.TextField(blank=True, default='')),
                ('socials', models.JSONField(blank=True, default=dict)),
                ('featured_collection_id', models.IntegerField(blank=True, null=True)),
                ('featured_product_ids', models.JSONField(blank=True, default=list, help_text='List of featured product IDs')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
