# Generated by Django 5.0.7 on 2025-12-08 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_payoutrequest_completed_at_and_more'),
    ]

    operations = []
