# Generated by Django 5.0.7 on 2026-01-13 11:27

import backend.app.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_payoutrequest_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', validators=[backend.app.validators.FileValidator()]),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='payoutrequest',
                    name='completed_at',
                    field=models.DateTimeField(blank=True, db_column='processed_at', null=True),
                ),
                migrations.AlterField(
                    model_name='payoutrequest',
                    name='completed_by',
                    field=models.ForeignKey(blank=True, db_column='processed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_payouts', to=settings.AUTH_USER_MODEL),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', validators=[backend.app.validators.FileValidator()]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', validators=[backend.app.validators.FileValidator()]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial_images/', validators=[backend.app.validators.FileValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[backend.app.validators.FileValidator()]),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='app_order_status_4eece7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='app_order_user_id_bedb90_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['admin_approved', 'vendor_can_process'], name='app_order_admin_a_75a4ed_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='app_order_created_56751d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', 'approval_status'], name='app_product_vendor__31c9f0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='app_product_categor_4f998c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['featured', 'created_at'], name='app_product_feature_955bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='app_product_slug_10a1ae_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='app_product_created_587a36_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='app_transac_status_f05b42_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['order'], name='app_transac_order_i_f6eb62_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['admin_approved'], name='app_transac_admin_a_2eaadd_idx'),
        ),
    ]
