# Generated by Django 5.2.10 on 2026-06-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_notification_notification_type_storereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_approved', 'Order Approved'), ('order_rejected', 'Order Rejected'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('payout_approved', 'Payout Approved'), ('payout_rejected', 'Payout Rejected'), ('product_approved', 'Product Approved'), ('product_rejected', 'Product Rejected'), ('vendor_approved', 'Vendor Approved'), ('vendor_rejected', 'Vendor Rejected'), ('order', 'Order Update'), ('store_review', 'Store Review')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='app_notific_recipie_5e4cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_responded'], name='app_notific_recipie_74b651_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='app_notific_created_1bdda8_idx'),
        ),
    ]
